export const database = [{
    id: 1,
    category: 'books',
    description: `Discover a wide selection of books across classics, history, psychology, art, sports, and more. Whether you're looking for timeless literature or modern insights, explore stories and knowledge in multiple languages.`,
    items: [{
        id: 1,
        imageUrl: 'https://covers.openlibrary.org/b/id/8231856-L.jpg',
        name: 'Crime and Punishment',
        author: 'Fyodor Dostoevsky',
        description: 'A psychological drama exploring morality, guilt, and redemption in Saint Petersburg.',
        price: 9.99,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'classics'
    },
    {
        id: 2,
        imageUrl: 'https://covers.openlibrary.org/b/id/8228691-L.jpg',
        name: 'The Brothers Karamazov',
        author: 'Fyodor Dostoevsky',
        description: 'A philosophical novel about faith, doubt, and free will.',
        price: 12.50,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'classics'
    },
    {
        id: 3,
        imageUrl: 'https://covers.openlibrary.org/b/id/8235083-L.jpg',
        name: 'Atomic Habits',
        author: 'James Clear',
        description: 'A practical guide to building good habits and breaking bad ones.',
        price: 11.20,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'psychology'
    },
    {
        id: 4,
        imageUrl: 'https://covers.openlibrary.org/b/id/8091016-L.jpg',
        name: 'The Art of War',
        author: 'Sun Tzu',
        description: 'An ancient Chinese treatise on military strategy and tactics.',
        price: 6.99,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'history'
    },
    {
        id: 5,
        imageUrl: 'https://covers.openlibrary.org/b/id/8234145-L.jpg',
        name: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        description: 'A fantasy adventure about Bilbo Baggins and his unexpected journey.',
        price: 8.99,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'classics'
    },
    {
        id: 6,
        imageUrl: 'https://covers.openlibrary.org/b/id/8231994-L.jpg',
        name: 'Под игото',
        author: 'Иван Вазов',
        description: 'Класически български роман за живота по време на османското владичество.',
        price: 7.80,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'classics'
    },
    {
        id: 7,
        imageUrl: 'https://covers.openlibrary.org/b/id/8235116-L.jpg',
        name: 'Бай Ганьо',
        author: 'Алеко Константинов',
        description: 'Сатиричен роман, описващ приключенията на Бай Ганьо.',
        price: 6.40,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'BG',
        genre: 'humour'
    },
    {
        id: 8,
        imageUrl: 'https://covers.openlibrary.org/b/id/8225631-L.jpg',
        name: 'История славянобългарска',
        author: 'Паисий Хилендарски',
        description: 'Произведение, събудило българското национално съзнание.',
        price: 9.10,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'history'
    },
    {
        id: 9,
        imageUrl: 'https://covers.openlibrary.org/b/id/8225261-L.jpg',
        name: 'Железният светилник',
        author: 'Димитър Талев',
        description: 'Роман за българското възраждане и борбата за църковна независимост.',
        price: 8.60,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'BG',
        genre: 'classics'
    },
    {
        id: 10,
        imageUrl: 'https://covers.openlibrary.org/b/id/8235088-L.jpg',
        name: 'Психология на успеха',
        author: 'Иван Петров',
        description: 'Книга за личностно развитие и изграждане на успешни навици.',
        price: 10.50,
        rating: [1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'psychology'
    },
    {
        id: 11,
        imageUrl: 'https://covers.openlibrary.org/b/id/8319256-L.jpg',
        name: 'Don Quichotte',
        author: 'Miguel de Cervantes',
        description: 'Un roman satirique sur un noble obsédé par la chevalerie.',
        price: 10.99,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'classics'
    },
    {
        id: 12,
        imageUrl: 'https://covers.openlibrary.org/b/id/8231850-L.jpg',
        name: 'Le Petit Prince',
        author: 'Antoine de Saint-Exupéry',
        description: 'Un conte poétique et philosophique pour petits et grands.',
        price: 7.40,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'FR',
        genre: 'classics'
    },
    {
        id: 13,
        imageUrl: 'https://covers.openlibrary.org/b/id/8231990-L.jpg',
        name: 'L\'Étranger',
        author: 'Albert Camus',
        description: 'Un roman existentialiste sur l’absurdité de la vie.',
        price: 8.20,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'classics'
    },
    {
        id: 14,
        imageUrl: 'https://covers.openlibrary.org/b/id/8235088-L.jpg',
        name: 'L\'Art moderne',
        author: 'Claire Dubois',
        description: 'Une introduction accessible à l’histoire de l’art moderne.',
        price: 15.60,
        rating: [1, 1, 1],
        discount: false,
        lang: 'FR',
        genre: 'art'
    },
    {
        id: 15,
        imageUrl: 'https://covers.openlibrary.org/b/id/8228691-L.jpg',
        name: 'Psychologie positive',
        author: 'Jean Martin',
        description: 'Un guide pratique pour développer une mentalité positive.',
        price: 9.30,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'psychology'
    },
    {
        id: 16,
        imageUrl: 'https://covers.openlibrary.org/b/id/8235083-L.jpg',
        name: 'Deep Work',
        author: 'Cal Newport',
        description: 'Rules for focused success in a distracted world.',
        price: 13.99,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'psychology'
    },
    {
        id: 17,
        imageUrl: 'https://covers.openlibrary.org/b/id/8234145-L.jpg',
        name: 'The History of Rome',
        author: 'Mary Beard',
        description: 'A detailed history of ancient Rome.',
        price: 14.20,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'history'
    },
    {
        id: 18,
        imageUrl: 'https://covers.openlibrary.org/b/id/8231994-L.jpg',
        name: 'Спортна психология',
        author: 'Георги Иванов',
        description: 'Книга за психическата подготовка в спорта.',
        price: 11.00,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'sports'
    },
    {
        id: 19,
        imageUrl: 'https://covers.openlibrary.org/b/id/8235116-L.jpg',
        name: 'The Art of Humor',
        author: 'John Smith',
        description: 'Exploring the science and craft of comedy.',
        price: 8.50,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'humour'
    },
    {
        id: 20,
        imageUrl: 'https://covers.openlibrary.org/b/id/8235088-L.jpg',
        name: 'Histoire du sport',
        author: 'Pierre Laurent',
        description: 'Une exploration de l’histoire du sport en Europe.',
        price: 12.10,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'FR',
        genre: 'sports'
    }]
},
{
    id: 2,
    category: 'magazines',
    description: `Browse our collection of magazines covering current events, culture, sports, psychology, and the arts. Stay informed and inspired with fresh perspectives from around the world.`,
    items: [{
        id: 1,
        imageUrl: 'https://covers.openlibrary.org/b/id/240727-L.jpg',
        name: 'National Geographic',
        author: 'National Geographic Society',
        description: 'A magazine featuring science, geography, history, and world culture.',
        price: 5.99,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'history'
    },
    {
        id: 2,
        imageUrl: 'https://covers.openlibrary.org/b/id/240726-L.jpg',
        name: 'Time',
        author: 'Time USA LLC',
        description: 'Weekly magazine covering politics, current events, and culture.',
        price: 4.50,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'history'
    },
    {
        id: 3,
        imageUrl: 'https://covers.openlibrary.org/b/id/240728-L.jpg',
        name: 'Sports Illustrated',
        author: 'The Arena Group',
        description: 'Magazine focused on sports news and athlete features.',
        price: 6.20,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'sports'
    },
    {
        id: 4,
        imageUrl: 'https://covers.openlibrary.org/b/id/240729-L.jpg',
        name: 'Psychology Today',
        author: 'Sussex Publishers',
        description: 'Magazine dedicated to psychology and human behavior.',
        price: 7.00,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'psychology'
    },
    {
        id: 5,
        imageUrl: 'https://covers.openlibrary.org/b/id/240730-L.jpg',
        name: 'Art Review',
        author: 'ArtReview Ltd',
        description: 'Contemporary art magazine covering global exhibitions.',
        price: 8.90,
        rating: [1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'art'
    },
    {
        id: 6,
        imageUrl: 'https://covers.openlibrary.org/b/id/240731-L.jpg',
        name: 'Българска история',
        author: 'История ООД',
        description: 'Списание, посветено на българската и световната история.',
        price: 4.80,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'BG',
        genre: 'history'
    },
    {
        id: 7,
        imageUrl: 'https://covers.openlibrary.org/b/id/240732-L.jpg',
        name: 'Спорт и здраве',
        author: 'Медия Груп',
        description: 'Списание за спорт, фитнес и активен начин на живот.',
        price: 3.90,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'sports'
    },
    {
        id: 8,
        imageUrl: 'https://covers.openlibrary.org/b/id/240733-L.jpg',
        name: 'Психология днес',
        author: 'Психология БГ',
        description: 'Актуални теми за личностно развитие и психично здраве.',
        price: 5.20,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'BG',
        genre: 'psychology'
    },
    {
        id: 9,
        imageUrl: 'https://covers.openlibrary.org/b/id/240734-L.jpg',
        name: 'Изкуство и култура',
        author: 'Културен център',
        description: 'Списание за съвременно и класическо изкуство.',
        price: 6.10,
        rating: [1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'art'
    },
    {
        id: 10,
        imageUrl: 'https://covers.openlibrary.org/b/id/240735-L.jpg',
        name: 'Хумор',
        author: 'Весела преса',
        description: 'Сатирично списание с карикатури и коментари.',
        price: 3.50,
        rating: [1, 1],
        discount: true,
        lang: 'BG',
        genre: 'humour'
    },
    {
        id: 11,
        imageUrl: 'https://covers.openlibrary.org/b/id/240736-L.jpg',
        name: 'Le Monde Diplomatique',
        author: 'Le Monde',
        description: 'Magazine français d’analyse politique et sociale.',
        price: 6.40,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'FR',
        genre: 'history'
    },
    {
        id: 12,
        imageUrl: 'https://covers.openlibrary.org/b/id/240737-L.jpg',
        name: 'L\'Équipe Magazine',
        author: 'Groupe Amaury',
        description: 'Magazine sportif avec interviews et reportages exclusifs.',
        price: 5.60,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'sports'
    },
    {
        id: 13,
        imageUrl: 'https://covers.openlibrary.org/b/id/240738-L.jpg',
        name: 'Psychologies',
        author: 'Reworld Media',
        description: 'Magazine dédié au bien-être et au développement personnel.',
        price: 6.80,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'FR',
        genre: 'psychology'
    },
    {
        id: 14,
        imageUrl: 'https://covers.openlibrary.org/b/id/240739-L.jpg',
        name: 'Beaux Arts',
        author: 'Beaux Arts & Cie',
        description: 'Magazine sur l’art classique et contemporain.',
        price: 7.90,
        rating: [1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'art'
    },
    {
        id: 15,
        imageUrl: 'https://covers.openlibrary.org/b/id/240740-L.jpg',
        name: 'Humour Magazine',
        author: 'Rire Éditions',
        description: 'Magazine satirique avec caricatures et bandes dessinées.',
        price: 4.30,
        rating: [1, 1],
        discount: false,
        lang: 'FR',
        genre: 'humour'
    },
    {
        id: 16,
        imageUrl: 'https://covers.openlibrary.org/b/id/240741-L.jpg',
        name: 'History Monthly',
        author: 'Global Media',
        description: 'In-depth historical analysis and discoveries.',
        price: 6.70,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'history'
    },
    {
        id: 17,
        imageUrl: 'https://covers.openlibrary.org/b/id/240742-L.jpg',
        name: 'Art & Design',
        author: 'Creative Studio',
        description: 'Modern art, architecture, and creative trends.',
        price: 8.00,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'art'
    },
    {
        id: 18,
        imageUrl: 'https://covers.openlibrary.org/b/id/240743-L.jpg',
        name: 'Спортен свят',
        author: 'БГ Медия',
        description: 'Новини и анализи от света на спорта.',
        price: 4.20,
        rating: [1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'sports'
    },
    {
        id: 19,
        imageUrl: 'https://covers.openlibrary.org/b/id/240744-L.jpg',
        name: 'Le Sport Moderne',
        author: 'Paris Éditions',
        description: 'Magazine sur les tendances actuelles du sport.',
        price: 6.00,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'sports'
    },
    {
        id: 20,
        imageUrl: 'https://covers.openlibrary.org/b/id/240745-L.jpg',
        name: 'Mind & Brain',
        author: 'Science Press',
        description: 'Exploring neuroscience and human psychology.',
        price: 7.10,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'psychology'
    }]
},
{
    id: 3,
    category: 'dictionaries',
    description: `Explore comprehensive dictionaries designed to expand your vocabulary and deepen your understanding. From language references to specialized terminology, find the right resource for every need.`,
    items: [{
        id: 1,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546156-L.jpg',
        name: 'Oxford English Dictionary',
        author: 'Oxford University Press',
        description: 'Comprehensive dictionary of the English language with definitions and etymology.',
        price: 24.99,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'classics'
    },
    {
        id: 2,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546157-L.jpg',
        name: 'Merriam-Webster Dictionary',
        author: 'Merriam-Webster',
        description: 'Authoritative and up-to-date dictionary for English learners.',
        price: 19.50,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'classics'
    },
    {
        id: 3,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546158-L.jpg',
        name: 'English Synonyms & Antonyms',
        author: 'Collins',
        description: 'Dictionary focused on synonyms and antonyms for better writing.',
        price: 14.20,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'psychology'
    },
    {
        id: 4,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546159-L.jpg',
        name: 'Dictionary of Art Terms',
        author: 'Art Media Press',
        description: 'Reference guide for art terminology and artistic movements.',
        price: 17.80,
        rating: [1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'art'
    },
    {
        id: 5,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546160-L.jpg',
        name: 'Sports Terminology Dictionary',
        author: 'Global Sports Media',
        description: 'Dictionary explaining terminology used in various sports.',
        price: 16.40,
        rating: [1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'sports'
    },
    {
        id: 6,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546161-L.jpg',
        name: 'Български тълковен речник',
        author: 'БАН',
        description: 'Официален тълковен речник на съвременния български език.',
        price: 21.30,
        rating: [1, 1, 1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'classics'
    },
    {
        id: 7,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546162-L.jpg',
        name: 'Българо-английски речник',
        author: 'Просвета',
        description: 'Двуезичен речник с преводи и примери за употреба.',
        price: 18.60,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'BG',
        genre: 'classics'
    },
    {
        id: 8,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546163-L.jpg',
        name: 'Речник на чуждите думи',
        author: 'Наука и изкуство',
        description: 'Обяснения на чуждици и заемки в българския език.',
        price: 15.00,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'BG',
        genre: 'history'
    },
    {
        id: 9,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546164-L.jpg',
        name: 'Психологически термини',
        author: 'Медицинска преса',
        description: 'Речник на основните термини в психологията.',
        price: 13.70,
        rating: [1, 1, 1],
        discount: true,
        lang: 'BG',
        genre: 'psychology'
    },
    {
        id: 10,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546165-L.jpg',
        name: 'Спортен речник',
        author: 'Спорт БГ',
        description: 'Термини и понятия от различни видове спорт.',
        price: 12.40,
        rating: [1, 1],
        discount: false,
        lang: 'BG',
        genre: 'sports'
    },
    {
        id: 11,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546166-L.jpg',
        name: 'Le Petit Larousse',
        author: 'Larousse',
        description: 'Dictionnaire encyclopédique de la langue française.',
        price: 23.90,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'classics'
    },
    {
        id: 12,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546167-L.jpg',
        name: 'Dictionnaire Français-Anglais',
        author: 'Hachette',
        description: 'Dictionnaire bilingue pour étudiants et professionnels.',
        price: 19.80,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'FR',
        genre: 'classics'
    },
    {
        id: 13,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546168-L.jpg',
        name: 'Dictionnaire des synonymes',
        author: 'Éditions Robert',
        description: 'Guide complet des synonymes et nuances en français.',
        price: 16.50,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'psychology'
    },
    {
        id: 14,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546169-L.jpg',
        name: 'Dictionnaire des termes artistiques',
        author: 'Paris Éditions',
        description: 'Référence pour les termes liés à l’art et à l’esthétique.',
        price: 18.30,
        rating: [1, 1, 1],
        discount: false,
        lang: 'FR',
        genre: 'art'
    },
    {
        id: 15,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546170-L.jpg',
        name: 'Dictionnaire du sport',
        author: 'Sport France',
        description: 'Termes et expressions utilisés dans le sport moderne.',
        price: 14.60,
        rating: [1, 1, 1],
        discount: true,
        lang: 'FR',
        genre: 'sports'
    },
    {
        id: 16,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546171-L.jpg',
        name: 'English Idioms Dictionary',
        author: 'Oxford Press',
        description: 'Collection of common English idioms and expressions.',
        price: 13.90,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'EN',
        genre: 'humour'
    },
    {
        id: 17,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546172-L.jpg',
        name: 'Български правописен речник',
        author: 'Просвета',
        description: 'Официални правила за правопис и пунктуация.',
        price: 17.20,
        rating: [1, 1, 1, 1, 1],
        discount: true,
        lang: 'BG',
        genre: 'classics'
    },
    {
        id: 18,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546173-L.jpg',
        name: 'Dictionnaire historique',
        author: 'Université de Paris',
        description: 'Dictionnaire spécialisé dans les termes historiques.',
        price: 20.40,
        rating: [1, 1, 1, 1],
        discount: false,
        lang: 'FR',
        genre: 'history'
    },
    {
        id: 19,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546174-L.jpg',
        name: 'Business English Dictionary',
        author: 'Cambridge',
        description: 'Essential vocabulary for business and finance.',
        price: 18.90,
        rating: [1, 1, 1, 1],
        discount: true,
        lang: 'EN',
        genre: 'history'
    },
    {
        id: 20,
        imageUrl: 'https://covers.openlibrary.org/b/id/5546175-L.jpg',
        name: 'Речник на хумористични изрази',
        author: 'Весела книга',
        description: 'Сборник от забавни и хумористични изрази.',
        price: 11.50,
        rating: [1, 1],
        discount: false,
        lang: 'BG',
        genre: 'humour'
    }
    ]
}]